### ISSUE TITLE
when use "zh-yue"    occured HTTPError: 404 Client Error

### ISSUE THREAD

**Issue by evilkjoker** [pndurette/gTTS#106]
my code 

```
from gtts import gTTS
tts = gTTS(text='大家好', lang='zh-yue')          
tts.save("test0.mp3") 
```

failed

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joker/git/voicerecog/cmd/lib/python3.6/site-packages/gtts/tts.py", line 111, in save
    self.write_to_fp(f)
  File "/Users/joker/git/voicerecog/cmd/lib/python3.6/site-packages/gtts/tts.py", line 144, in write_to_fp
    r.raise_for_status()
  File "/Users/joker/git/voicerecog/cmd/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://translate.google.com/translate_tts?ie=UTF-8&q=%E5%A4%A7%E5%AE%B6%E5%A5%BD&tl=zh-yue&ttsspeed=1&total=1&idx=0&client=tw-ob&textlen=3&tk=461496.97530
```

python version 

```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55)
```

**Comment by evilkjoker** [comment]
record to https://cloud.google.com/translate/docs/languages
it looks like zh-yue not supported any more

**Comment by pndurette** [comment]
Yes, unfortunately (and for an unknown reason), Google has removed Cantonese from the Google Translate TTS engine. I haven't updated and released `master` to change this yet because gTTS `2.0.0` is practically done now (polishing docs). It's what's making the `master` tests fail too.

**Comment by evilkjoker** [comment]
thanks for reply
