### ISSUE TITLE
The module examples do not work in Windows

### ISSUE THREAD

**Issue by s4chin** [pndurette/gTTS#11]
The instantiate example and the file like object example do not work in Windows.
I am using Windows 10, 64 bit.
Both give the same error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\gtts\tts.py", line 90, in save
    self.write_to_fp(f)
  File "C:\Python27\lib\site-packages\gtts\tts.py", line 104, in write_to_fp
    r = requests.get(self.GOOGLE_TTS_URL, params=payload)
  File "C:\Python27\lib\site-packages\requests\api.py", line 60, in get
    return request('get', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 48, in request
    session = sessions.Session()
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 284, in __init
__
    self.headers = default_headers()
  File "C:\Python27\lib\site-packages\requests\utils.py", line 552, in default_h
eaders
    'User-Agent': default_user_agent(),
  File "C:\Python27\lib\site-packages\requests\utils.py", line 521, in default_u
ser_agent
    _implementation = platform.python_implementation()
  File "C:\Python27\Lib\platform.py", line 1456, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1422, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.3 |CUSTOM| (default, Aug
8 2013, 05:34:32) [MSC v.1500 32 bit (Intel)]'
```

**Comment by pndurette** [comment]
Hi @s4chin, I have never tested it on Windows. Officially, I don't support it (as per package metadata), but it should work.

On quick glance, looks like the error comes from `requests` though (which supports Windows, so I can't really tell what the real issue is). Does `requests` work by itself? IIRC, installing it on Windows requires extra/special steps. I would try doing that first, and then trying the examples again.

**Comment by s4chin** [comment]
Hey @pndurette, well, this is weird. The examples work fine if I add these lines before running the examples:
```
import sys
sys.version = '2.7.3 (default, Apr 12 2012, 14:30:37) [MSC v.1500 32 bit (Intel)]'
```
Saw this [here](http://stackoverflow.com/questions/19105255/praw-failed-to-parse-cpython-sys-version-when-creating-reddit-object) and tried it and it works. Just wanted to let you know.
