### ISSUE TITLE
NewConnectionError

### ISSUE THREAD

**Issue by The-Gupta** [pndurette/gTTS#133]
I'm not sure why this error comes. Is there a over/unusual traffic detection and termination of service?

Error is:

> gTTSError: Connection error during token calculation: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000027D99671D30>: Failed to establish a new connection: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted',))

Stack trace

```
Traceback (most recent call last):

  File "<ipython-input-39-5bc3d5f7fd6b>", line 106, in <module>
    print(inputSent, '\n\n', theFun(folder_name + '\\', inputSent, sphinx_flag = 1), '\n\n\n\n')

  File "<ipython-input-39-5bc3d5f7fd6b>", line 25, in theFun
    tts.save(path + 'input.wav')

  File "C:\Anaconda3\lib\site-packages\gtts\tts.py", line 247, in save
    self.write_to_fp(f)

  File "C:\Anaconda3\lib\site-packages\gtts\tts.py", line 192, in write_to_fp
    str(e))

gTTSError: Connection error during token calculation: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000027D994DC668>: Failed to establish a new connection: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted',))


```

**Comment by The-Gupta** [comment]
Trying further I get - **Max retries exceeded with url**

```
Traceback (most recent call last):

  File "<ipython-input-41-3f7646f90ea4>", line 106, in <module>
    print(inputSent, '\n\n', theFun(folder_name + '\\', inputSent, sphinx_flag = 1), '\n\n\n\n')

  File "<ipython-input-41-3f7646f90ea4>", line 25, in theFun
    tts.save(path + 'input.wav')

  File "C:\Anaconda3\lib\site-packages\gtts\tts.py", line 247, in save
    self.write_to_fp(f)

  File "C:\Anaconda3\lib\site-packages\gtts\tts.py", line 224, in write_to_fp
    raise gTTSError(str(e))

gTTSError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /translate_tts?q=Alexa.+Who+is+Narendra+Modi%3F&ttsspeed=1&tk=770226.900928&idx=0&ie=UTF-8&client=tw-ob&textlen=28&tl=en&total=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000027D9970F128>: Failed to establish a new connection: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted',))
```

**Comment by pndurette** [comment]
Thanks for this and trying things out. I have to check what's up. Looks like it's possibly Google-side limiting (which could be understandable). Might need to build some sort of caching on top (it's also something that's crossed my mind for gTTS). But I have to investigate.
