### ISSUE TITLE
 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by shiva9u** [pndurette/gTTS#15]
from gtts import gTTS

tts = gTTS(text="hello", lang='en')
tts.save('F:say.mp3')

Traceback (most recent call last):
  File "F:\testaudio.py", line 5, in <module>
    tts.save('F:say.mp3')
  File "C:\Python27\lib\site-packages\gtts\tts.py", line 90, in save
    self.write_to_fp(f)
  File "C:\Python27\lib\site-packages\gtts\tts.py", line 108, in write_to_fp
    r.raise_for_status()
  File "C:\Python27\lib\site-packages\requests\models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://translate.google.com/translate_tts?textlen=5&idx=0&q=hello&tl=en&client=t&total=1&ie=UTF-8

**Comment by pndurette** [comment]
Aware of this. Google locked down the API this lib uses. I might change it to Bing's equivalent. See issue #14 and perhaps other enhancements, such as caching to reduce the times these unrestricted endpoints are hit.

**Comment by pndurette** [comment]
@shiva9u Fixed in #17, updated `gTTS` to `1.1.2`.
