### ISSUE TITLE
Google has changed their API yet again. [FIXED—Please update `gTTS-token`!]

### ISSUE THREAD

**Issue by fidelhuang** [pndurette/gTTS#151]
Google has changed their API yet again.
I use GTTS 2.0.1  and gTTS-token==1.1.2

error log：
gtts.tts - WARNING - Unable to get language list: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/bin/gtts-cli", line 11, in <module>
    load_entry_point('gTTS==2.0.1', 'console_scripts', 'gtts-cli')()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/gtts/cli.py", line 194, in tts_cli
    tts.write_to_fp(output)
  File "/usr/local/lib/python3.5/site-packages/gtts/tts.py", line 187, in write_to_fp
    part_tk = self.token.calculate_token(part)
  File "/usr/local/lib/python3.5/site-packages/gtts_token/gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "/usr/local/lib/python3.5/site-packages/gtts_token/gtts_token.py", line 58, in _get_token_key
    tkk_expr = re.search("tkk:\'(.+?)\'", line).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Does anybody have an idea how to fix this?

**Comment by doruchan** [comment]
Hi, 

I have requested a pull request to the gtts_token developer. In the meanwhile my working version is here:
https://github.com/doruchan/gTTS-token/blob/fix_token/gtts_token/gtts_token.py

cheers

**Comment by fidelhuang** [comment]
> Hi,
> 
> I have requested a pull request to the gtts_token developer. In the meanwhile my working version is here:
> https://github.com/doruchan/gTTS-token/blob/fix_token/gtts_token/gtts_token.py
> 
> cheers

thanks, work well.

**Comment by Boudewijn26** [comment]
[gTTS-token v1.1.3 has been released](https://github.com/Boudewijn26/gTTS-token/releases/tag/v1.1.3). Thanks everyone for the quick fixes. Please verify if this actually fixes the issue for you

**Comment by Sispheor** [comment]
I don't see the usage of the lib gtts-token in this lib (setup.py).
The fix will be back ported here? 

Thanks.
