### ISSUE TITLE
Cannot install using pip install gTTS

### ISSUE THREAD

**Issue by adisdhiv** [pndurette/gTTS#167]
Collecting gTTS
Installing collected packages: gTTS
Exception:
Traceback (most recent call last):
  File "c:\users\dhivya\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\cli\base_command.py", line 143, in main
    status = self.run(options, args)
  File "c:\users\dhivya\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\commands\install.py", line 366, in run
    use_user_site=options.use_user_site,
  File "c:\users\dhivya\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\req\__init__.py", line 49, in install_given_reqs
    **kwargs
  File "c:\users\dhivya\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\req\req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "c:\users\dhivya\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\req\req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "c:\users\dhivya\appdata\local\programs\python\python35\lib\site-packages\pip\_internal\wheel.py", line 326, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: gTTS .dist-info directory not found

**Comment by pndurette** [comment]
Looks like a setup error, maybe your `setuptools` is old. Try:
```
pip install setuptools --upgrade
```

**Comment by pndurette** [comment]
And `pip` for that matter:
```
pip install pip --upgrade
```

**Comment by adisdhiv** [comment]
Even after trying the above, still showing same error

**Comment by pndurette** [comment]
@adisdhiv Can you try this and let me know?
https://github.com/pndurette/gTTS/issues/158#issuecomment-446411841

**Comment by whtitefall** [comment]
> @adisdhiv Can you try this and let me know?
> [#158 (comment)](https://github.com/pndurette/gTTS/issues/158#issuecomment-446411841)

works for me

**Comment by shekharkoirala** [comment]
```
(whereis) ekbana@ekbana-3:~/projects/vo-$ pip3 install setuptools --upgrade
Requirement already up-to-date: setuptools in /home/ekbana/projects/whereis/lib/python3.5/site-packages (41.0.1)
(whereis) ekbana@ekbana-3:~/projects/vo$ pip3 install pip --upgrade
Requirement already up-to-date: pip in /home/ekbana/projects/whereis/lib/python3.5/site-packages (19.1)
(whereis) ekbana@ekbana-3:~/projects/vo$ pip3 install gTTS
Collecting gTTS
Installing collected packages: gTTS
ERROR: Exception:
Traceback (most recent call last):
  File "/home/ekbana/projects/whereis/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/home/ekbana/projects/whereis/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/home/ekbana/projects/whereis/lib/python3.5/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/home/ekbana/projects/whereis/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 922, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/ekbana/projects/whereis/lib/python3.5/site-packages/pip/_internal/req/req_install.py", line 448, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/ekbana/projects/whereis/lib/python3.5/site-packages/pip/_internal/wheel.py", line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: gTTS .dist-info directory not found

```

**Comment by shekharkoirala** [comment]
This solved my issue
`(whereis) ekbana@ekbana-3:~/projects/vo$ pip3 install --no-cache-dir gTTS
`
