### ISSUE TITLE
Error During Installing gTTS 

### ISSUE THREAD

**Issue by skp1996** [pndurette/gTTS#186]
`(base) C:\WINDOWS\system32>pip install setuptools --upgrade
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\pip\_internal\__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "c:\programdata\anaconda3\lib\site-packages\pip\_internal\cli\autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "c:\programdata\anaconda3\lib\site-packages\pip\_internal\cli\main_parser.py", line 11, in <module>
    from pip._internal.commands import (
  File "c:\programdata\anaconda3\lib\site-packages\pip\_internal\commands\__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "c:\programdata\anaconda3\lib\site-packages\pip\_internal\commands\completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "c:\programdata\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 26, in <module>
    from pip._internal.index import PackageFinder
  File "c:\programdata\anaconda3\lib\site-packages\pip\_internal\index.py", line 11, in <module>
    from pip._vendor import html5lib, requests, six
  File "c:\programdata\anaconda3\lib\site-packages\pip\_vendor\html5lib\__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "c:\programdata\anaconda3\lib\site-packages\pip\_vendor\html5lib\html5parser.py", line 8, in <module>
    from . import _tokenizer
  File "c:\programdata\anaconda3\lib\site-packages\pip\_vendor\html5lib\_tokenizer.py", line 16, in <module>
    from ._trie import Trie
  File "c:\programdata\anaconda3\lib\site-packages\pip\_vendor\html5lib\_trie\__init__.py", line 3, in <module>
    from .py import Trie as PyTrie
  File "c:\programdata\anaconda3\lib\site-packages\pip\_vendor\html5lib\_trie\py.py", line 6, in <module>
    from ._base import Trie as ABCTrie
ImportError: cannot import name 'Trie'`

**Comment by pndurette** [comment]
Hey @skp1996. Do you have a bit more info about what you're doing? OS, Python version, etc?

**Comment by pndurette** [comment]
As of `v2.0.4`, `gTTS` is now build as a wheel package, which should simplify a lot of installs! Let me know!
