### ISSUE TITLE
how to set proxy

### ISSUE THREAD

**Issue by Iseuwei** [pndurette/gTTS#261]
Traceback (most recent call last):
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
    raise err
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001E0417CEAF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /_/TranslateWebserverUi/data/batchexecute (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E0417CEAF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\gtts\tts.py", line 266, in write_to_fp
    r = s.send(request=pr,
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /_/TranslateWebserverUi/data/batchexecute (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E0417CEAF0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Iseuwei/WorkSpace/PyCharm/stockcross/test.py", line 16, in <module>
    start()
  File "D:/Iseuwei/WorkSpace/PyCharm/stockcross/test.py", line 8, in start
    tts.save('hello.mp3')
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\gtts\tts.py", line 314, in save
    self.write_to_fp(f)
  File "C:\Iseuwei\Tools\Anaconda3\envs\tf10-gpu\lib\site-packages\gtts\tts.py", line 281, in write_to_fp
    raise gTTSError(tts=self)
gtts.tts.gTTSError: Failed to connect. Probable cause: Unknown

**Comment by pndurette** [comment]
Hi, sorry for the late reply! This could be related to an issue that's ongoing, but to be sure can you share the code that's generating the error?

**Comment by pndurette** [comment]
Hello! gTTS `v2.2.2` is out which quite possibly fixes your issue!
