### ISSUE TITLE
Issue with TTS API?

### ISSUE THREAD

**Issue by Subsical** [pndurette/gTTS#264]
Using this on a Discord bot, it was working until yesterday but now I get this error:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/subs/bots/bot-env/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 874, in on_message
    tts.save(f"/home/subs/bots/Blocbot/Text to Speech/{audio_name}.mp3")
  File "/home/subs/bots/bot-env/lib/python3.8/site-packages/gtts/tts.py", line 312, in save
    self.write_to_fp(f)
  File "/home/subs/bots/bot-env/lib/python3.8/site-packages/gtts/tts.py", line 294, in write_to_fp
    raise gTTSError(tts=self, response=r)
gtts.tts.gTTSError: 200 (OK) from TTS API. Probable cause: Unknown
```

**Comment by Subsical** [comment]
Nevermind, it's fine now
