### ISSUE TITLE
gtts-cli command failing

### ISSUE THREAD

**Issue by PrincessMiki** [pndurette/gTTS#311]
## Prerequisites
* [x] Did you make sure a similar [issue](../) didn't exist?
* [x] Did you update gTTS to the latest? (`pip install --upgrade gTTS`)

**Hi again, new computer, new install, but new problem. So my fix from before didn't fix this!**

## Current Behaviour (steps to reproduce)

```

When i used the code:
gtts-cli 'hello' --output hello.mp3

it gives me:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 584, in _build_master
ws.require(**requires**)
File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 901, in require
needed = self.resolve(parse_requirements(requirements))
File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 792, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (gTTS 2.2.3 (/home/toni/.local/lib/python3.8/site-packages), Requirement.parse('gTTS==2.0.3'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/gtts-cli", line 6, in <module>
from pkg_resources import load_entry_point
File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 3254, in <module>
def _initialize_master_working_set():
File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 3237, in _call_aside
f(*args, **kwargs)
File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 3266, in _initialize_master_working_set
working_set = WorkingSet._build_master()
File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 586, in _build_master
return cls._build_from_requirements(**requires**)
File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 599, in _build_from_requirements
dists = ws.resolve(reqs, Environment())
File "/usr/lib/python3/dist-packages/pkg_resources/**init**.py", line 787, in resolve
raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gTTS==2.0.3' distribution was not found and is required by the application

## Environment
<!--- Include as many relevant details about the environment you experienced the bug in -->
* gTTS version: 2.2.3
* Operating System version: ubuntu 20.04.02

**Comment by pndurette** [comment]
Can't reproduce, no more comments since last year.
