### ISSUE TITLE
I am new to gtts so please help me ,Is there any limit with the number of times i can use the gtts module as after few days of using i got the error of Max retries exceeded with the url and some connection error

### ISSUE THREAD

**Issue by vikesh8860** [pndurette/gTTS#61]
The exact error is

```
(Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connection.py", line 135, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python\lib\site-packages\requests\packages\urllib3\util\connection.py", line 66, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "C:\Python\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 782, in _validate_conn
    conn.connect()
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connection.py", line 215, in connect
    conn = self._new_conn()
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connection.py", line 144, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000132FB57A438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python\lib\site-packages\requests\packages\urllib3\util\retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000132FB57A438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    tts.save('Hello.mp3')
  File "C:\Python\lib\site-packages\gtts\tts.py", line 94, in save
    self.write_to_fp(f)
  File "C:\Python\lib\site-packages\gtts\tts.py", line 107, in write_to_fp
    'tk' : self.token.calculate_token(part)}
  File "C:\Python\lib\site-packages\gtts_token\gtts_token.py", line 28, in calculate_token
    seed = self._get_token_key()
  File "C:\Python\lib\site-packages\gtts_token\gtts_token.py", line 58, in _get_token_key
    response = requests.get("https://translate.google.com/")
  File "C:\Python\lib\site-packages\requests\api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python\lib\site-packages\requests\api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python\lib\site-packages\requests\adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000132FB57A438>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)))
```

**Comment by pndurette** [comment]
Since you mentioned it worked and after using it for a "for a few days" and then it stopped, It's possible you're indeed hammering the service and `translate.google.com` limited/blocked you. How often and quick do you do calls to the API?

**Comment by vikesh8860** [comment]
I have used at Max 20 to 30 times the gtts service after I have installed
this module on my machine

On Apr 8, 2017 12:54 AM, "Pierre-Nick Durette" <notifications@github.com>
wrote:

Since you mentioned it worked and after using it for a "for a few days" and
then it stopped, It's possible you're indeed hammering the service and
translate.google.com limited/blocked you. How often and quick do you do
calls to the API?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pndurette/gTTS/issues/61#issuecomment-292629509>, or mute
the thread

**Comment by pndurette** [comment]
Can you show me the snippet of code you're using? I can't really think of anything.

**Comment by vikesh8860** [comment]
I have previously created the tts object

> 
> 
>  def convert_speech_method(self):
> 
>         if len(self.text) >0:
>             lang = ''       #For storing the output language
>             selected_button_id = self.selected_button()
>             if selected_button_id == 1:
>                 lang = 'en-us'
>             elif selected_button_id ==2:
>                 lang = 'en-uk'
>             else:
>                 lang = 'hi'
>             mixer.music.load('C:\\Users\\Vikesh PC\\Desktop\\Main_Project\\Data\\hello.mp3')
>             self.tts = gTTS(self.text,lang)
>             try:
>                 shutil.rmtree(self.directory)
>             except: pass
>             if not os.path.exists(self.directory):
>                 os.makedirs(self.directory)
>             self.tts.save(self.directory+'\\'+'vbe179jakvhbra.mp3')
>             try:
>                 self.progress_bar.hide()
>             except: pass
>     #--------------------------------------------------------------------------------------

Now the error actually happened in this line

>  self.tts.save(self.directory+'\\\'+'vbe179jakvhbra.mp3')

**Comment by pndurette** [comment]
Hi! [gTTS 1.2.0](https://pypi.python.org/pypi/gTTS/1.2.0) was released. There's no changes that initially relates to your problem, but please try again. The problem might lie elsewhere. Sorry I can't help you much here.

**Comment by badripatro** [comment]
Hi,
My aim is to convert text to speech of 300000 caption files. 

I am using gTTS python library. here is the part of the code 

code:

-------------------------------------------------------------

var1='json/vqa_raw_train.json'
with open(var1) as json_data:
    d = json.load(json_data)
for i in range(num_caption):
	answer=d[i]['ans']
	tts = gTTS(answer)
	tts.save('../train2014_ans/'+str(d[i]['ques_id'])+'.mp3')

-----------------------------------------------------------------------


Then I am getting  this error  
-------------------------------------------------

Traceback (most recent call last):
  File "text_to_speech_train_final.py", line 15, in <module>
    tts.save('../train2014_ans/'+str(d[i]['ques_id'])+'.mp3')
  File "/home/user1/.local/lib/python2.7/site-packages/gtts/tts.py", line 247, in save
    self.write_to_fp(f)
  File "/home/user1/.local/lib/python2.7/site-packages/gtts/tts.py", line 221, in write_to_fp
    raise gTTSError(tts=self, response=r)
gtts.tts.gTTSError: 500 (Internal Server Error) from TTS API. Probable cause: Uptream API error. Try again later.

------------------------------------------------------------------------------------------------

Is there **any better way to convert text to speech  for large number files?**

**Comment by the-next-ceo** [comment]
is there any way that gTTS can read up to particular characters, like can we set a limit (for example up to 1000 characters from a .txt file)

**Comment by Sunda001** [comment]
> is there any way that gTTS can read up to particular characters, like can we set a limit (for example up to 1000 characters from a .txt file)

yes
