### ISSUE TITLE
gTTs not recognised in venv

### ISSUE THREAD

**Issue by dirkjobosman** [pndurette/gTTS#83]
I previously installed gTTS in venv and activated the same venv again, and ran my python script and got: "ImportError: No module named gtts". When, I then pip install gtts, I get the errors below. Any ideas why ? 
----------------------------------------------------------------------------------------
(venv) u:translate_text-to-speech username$ pip install gtts
Collecting gtts
Collecting gtts-token (from gtts)
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from gtts)
Collecting requests (from gtts)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->gtts)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->gtts)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->gtts)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->gtts)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Installing collected packages: idna, urllib3, certifi, chardet, requests, gtts-token, gtts
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/idna'
(venv) u:translate_text-to-speech username$

**Comment by ghunkins** [comment]
You're getting `OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/idna'`.

Maybe try `sudo pip install gtts`.

**Comment by pndurette** [comment]
It seems your `venv` is using some packages at the system level which its trying to update/use.

If you're using `virtualenv`, try `virtualenv --no-site-packages <yourenv>` to force only local environment packages.

**Comment by pndurette** [comment]
I'm closing this issue, let me know if the above fixes it!
